security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        your_db_provider:
            entity:
                class: App\Entity\User
                property: token
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
    access_control:
        - { path: /api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_USER }
        - { path: /, roles: ROLE_USER }
        - { path: /getQRCode, roles: ROLE_USER }
